variables:
  TEST_FOLDER: 'Epam.ASPNetCore.TourOperator.UnitTests'
stages:
  - build
  - test
  - deploy
before_script:
  - "Set-Location -Path rdrunet_q4_aspnetcore"
  - "dotnet restore"
build_job:
  stage: build
  tags: 
  - aspnet_core
  - dotnetcore
  only:
    - /^feature\/.*$/
  script:
    - "echo build..."
    - "dotnet build"
test_job:
  stage: test
  tags: 
  - aspnet_core
  - dotnetcore
  only:
    - /^feature\/.*$/
  script:
    - "echo test..."
    - "Set-Location -Path $TEST_FOLDER"
    - "dotnet test"
deploy_job:
  stage: deploy
  tags: 
  - aspnet_core
  - dotnetcore
  only:
    - /^feature\/.*$/
  script:
    - "echo deploy..."
    - "dotnet publish Epam.ASPNetCore.TourOperator.WEBUI -c Release -o ../artifacts/Epam.ASPNetCore.TourOperator.WEBUI -p:PublichProfile-Properties/CI_Pipline_artifacts.pubxml"
  artifacts:
   paths:
    - artifacts/Epam.ASPNetCore.TourOperator.WEBUI
   expire_in: 1 days

